/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.jscancella;

public class Library {
	public int unreadField = 42; // warning: URF_UNREAD_FIELD
	
    public boolean someLibraryMethod() {
        return true;
    }
}
